### ISSUE TITLE
[Bug Report] Title

### ISSUE THREAD

**Issue by topaz-h** [alovajs/scene#2]
### Reproduction Link

SyntaxError: Cannot use 'import.meta' outside a module

### Version

2.0.16

### Describe the Bug

![image](https://user-images.githubusercontent.com/54789070/230770035-05a700bb-2f3e-4567-82cf-99469e3adfe8.png)

Next.js 项目中不支持esm，请问只提供了esm版本吗

### Reproduce Steps

next

**Comment by JOU-amjs** [comment]
alova在2.2.0中已支持SSR
