### ISSUE TITLE
[Bug Report] usePagination initialData配置项无效

### ISSUE THREAD

**Issue by zzddlalala** [alovajs/scene#42]
### Reproduction Link

https://codesandbox.io/p/devbox/alova-usepagination-564lfk?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clq0oaqne00073b6h29vkhjls%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clq0oaqnd00023b6hm7cwa98w%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clq0oaqnd00043b6hsfki2uez%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clq0oaqne00063b6hkz8cmhat%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clq0oaqnd00023b6hm7cwa98w%2522%253A%257B%2522id%2522%253A%2522clq0oaqnd00023b6hm7cwa98w%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clq0oaqne00063b6hkz8cmhat%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clq0oaqne00053b6hl1vsdag4%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522npm%2520run%2520dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clq0oaqne00063b6hkz8cmhat%2522%252C%2522activeTabId%2522%253A%2522clq0oaqne00053b6hl1vsdag4%2522%257D%252C%2522clq0oaqnd00043b6hsfki2uez%2522%253A%257B%2522id%2522%253A%2522clq0oaqnd00043b6hsfki2uez%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clq0oaqnd00033b6hrdmh1k1o%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522npm%2520run%2520dev%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clq0oaqnd00033b6hrdmh1k1o%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### Version

1.2.1

#### 使用@alova/scene-vue中的usePagination, config中正确设置了initialData，total，data, 不立即请求，此时total，data并没有为initialData中预设的值。vue devtools中的显示如下：
![截屏2023-12-11 17 41 54](https://github.com/alovajs/scene/assets/18690631/d7ca0f71-04c8-4c13-b94b-f57f8642acbf)
#### 源码中初始化data和total的时候，似乎并没有考虑根据initialData来赋值。
https://github.com/alovajs/scene/blob/3e8fae8e2152ded045b695a68321a1c9e54c4645/src/hooks/pagination/usePagination.js#L64
https://github.com/alovajs/scene/blob/3e8fae8e2152ded045b695a68321a1c9e54c4645/src/hooks/pagination/usePagination.js#L144

### Reproduce Steps

1. const {data, total} = usePagination(getter, {initialData: { total: 3, data: [1,2,3]}, immediate: false})
2. data, total 值不正常

**Comment by JOU-amjs** [comment]
已修复，升级到v1.3.2可用
