### ISSUE TITLE
[Bug Report] 使用 usePagination 的过程中 Method 出现了 error，再次调用 reload 会没有效果

### ISSUE THREAD

**Issue by xuxchao** [alovajs/scene#53]
### Reproduction Link

无

### Version

1.4.2

### Describe the Bug

[Bug Report] 使用 usePagination 的过程中 Method 出现了 error，再次调用 reload 会调用失败

### Reproduce Steps

使用 usePagination 的过程中 Method 出现了 error，再次调用 reload 会没有效果

### Device / Browser / Browser Version

任意

**Comment by JOU-amjs** [comment]
升级到1.4.4解决此问题
