### ISSUE TITLE
[Bug Report] 在 Taro 中使用 useCaptcha 报错

### ISSUE THREAD

**Issue by LBinin** [alovajs/scene#63]
### Reproduction Link

无

### Version

1.5.0

### Describe the Bug

在 Taro + React + 微信小程序环境下，引入 `useCaptcha` 后，报错：`can not call useHooks until set the 'statesHook' at alova instance`

已经在创建实例的时候使用了 adapter-taro：
```ts
// 创建实例
import { createAlova } from 'alova'
import AdapterTaro from '@alova/adapter-taro'

export const user = createAlova({
  baseURL: BaseUrl.PROD,
  ...AdapterTaro(),
})
```

使用下面代码，在页面渲染阶段就报上面的错：

```ts
const getVerifyCode = (params) => user.Post('/verify_code/', params)

const {
  loading: sending,
  send: sendCaptcha,
  countdown,
} = useCaptcha(() => getVerifyCode({ phone }), {
  initialCountdown: 60,
})
```

### Reproduce Steps

在 Taro + React + 微信小程序场景下引入

**Comment by MeetinaXD** [comment]
感谢反馈！这边复现了你提到的问题，而且不仅限于useCaptcha，基本所有从scene包中导出的hook在使用时都有这个问题。包括vue和react环境

原因：暂时判断是taro打包的时候，在产物中包含了两个alova

<img width="767" alt="image" src="https://github.com/alovajs/scene/assets/40497962/682f6274-33bd-4f15-957d-4a2f6575d19a">

<img width="572" alt="image" src="https://github.com/alovajs/scene/assets/40497962/0813706b-9e41-402e-8136-de0311a88fb7">

这边尽快给出修复，有进一步消息会及时回复。

**Comment by JOU-amjs** [comment]
@LBinin 经过一番努力，发现是Taro的prebundle功能有bug，当`包A` 依赖 `包B`，且在项目中也使用了`包B`时，会出现两份`包B`的情况，在运行`npm run build:weapp`打包时由于是关闭的prebundle则功能是正常的。

因此你只需要在开发环境先关掉prebundle就可以正常运行了。
```js
// config/dev.ts
import type { UserConfigExport } from "@tarojs/cli";
export default {
   logger: {
    quiet: false,
    stats: true
  },
  compiler: {
    type: 'webpack5',
    prebundle: {
      // 关闭prebundle
      enable: false
    }
  },
  mini: {},
  h5: {}
} satisfies UserConfigExport
```

**Comment by JOU-amjs** [comment]
prebundle是Taro@3.5新增的功能（最新版本为Taro@3.6.x），感觉最近才上的功能。

![image](https://github.com/alovajs/scene/assets/29848971/3279ff78-43b6-4696-81f2-2e20e849dc8f)

[我已向taro提交一个issue](https://github.com/NervJS/taro/issues/15728)，等待修复
