### ISSUE TITLE
"getMethodKey" is not exported by "node_modules/alova/dist/alova.esm.js"

### ISSUE THREAD

**Issue by batchor** [alovajs/scene#68]
### Reproduction Link

none

### Version

1.6.2

### Describe the Bug

I recently updated @alova/scene-vue to `1.6.2` and alova to `3.0.5`, both of which are the latest version as of the posting of this issue.

However, the two packages seems to be incompatible and I got the following error message during building:

```
x Build failed in 6.90s
error during build:
node_modules/@alova/scene-vue/dist/alova-scene.esm.js (1:17): "getMethodKey" is not exported by "node_modules/alova/dist/alova.esm.js", imported by "node_modules/@alova/scene-vue/dist/alova-scene.esm.js"
```

### Reproduce Steps

npm i @alova/scene-vue@1.6.2
npm i alova@3.0.5

**Comment by JOU-amjs** [comment]
In alova@3.x, you need to import scene hooks from `alova/client`. the `@alova/scene-vue` is only compatible with 2.x. for more detailed from [v3 migration guidelines](https://alova.js.org/tutorial/project/migration/v2-to-v3)
